application: datadinascita
version: alpha-5
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /images/(.*\.(gif|png|jpg|ico))
  static_files: images/\1
  upload: images/(.*\.(gif|png|jpg|ico))

- url: /js/(.*\.js)
  static_files: js/\1
  upload: js/(.*\.js)

- url: /upload(.*)
  script: upload.py

- url: /test(.*)
  script: test.py

- url: /.*
  script: main.py

