application: datadinascita
version: alpha-5
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /images/(.*\.(gif|png|jpg|ico))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg|ico))

- url: /upload(.*)
  script: upload.py

- url: /test(.*)
  script: upload.py

- url: /.*
  script: main.py

